#!/bin/bash

############################################################################
#    This program is used to make binned mrcs from tifs that have already been gain-normalized
#    driftcorr_info_and_scripts_nogain is run by the subproccesses spawned by
#    OJcryo_unblur_tiff and does the actual unblur-led motion correction.
#    v0.11 - changed the way the script handles filenames to get around
#    names with multiple ".".
#
#    Copyright (C) 2018 Austin Dixon and Roxana Georgescu - Rockefeller University
#    "My esteemed colleague Roxana contributed a significant amount of
#    initial code on this script." - Austin
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
###########################################################################

#gainref=${!#}	# get last parameter -> gain reference
UB=/programs/x86_64-linux/unblur/1.0.2/bin/unblur	# default to unblur 1.0.2

#n=(($#-1))

# loop through all the tifs in the parameter array
for i in "${@:1:$#}"; do
###################
# " Covert Tif to mrc "
###################
  file=$(echo ${i} | cut -f 1 -d '.')	# get filename without extension
  tif2mrc $i $file.mrc > output.txt

####################################"
# "Gain reference correction and bin 2"
####################################"
#  clip mult -n 16 ${i}.mrc $gainref ${i}_gaincorr.mrc >> output.txt
  binvol -x 2 -y 2 -z 1 $file.mrc $file_binned.mrc >> output.txt


###############################################################
#" Move, rename, and delete junk of ${i}_driftcorr.mrc "
###############################################################
  mv $file_binned.mrc driftcorr_mrc
  mv ${i} Finished_tif
done

exit 1

