#!/bin/bash

# This program is used to make binned mrcs from tifs that have been gain-normalized

#gainref=${!#}	# get last parameter -> gain reference
UB=/programs/x86_64-linux/unblur/1.0.2/bin/unblur	# default to unblur 1.0.2

#n=(($#-1))

# loop through all the tifs in the parameter array
for i in "${@:1:$#}"; do
###################
# " Covert Tif to mrc "
###################
  file=$(echo ${i} | cut -f 1 -d '.')	# get filename without extension
  tif2mrc $i $file.mrc > output.txt

####################################"
# "Gain reference correction and bin 2"
####################################"
#  clip mult -n 16 ${i}.mrc $gainref ${i}_gaincorr.mrc >> output.txt
  binvol -x 2 -y 2 -z 1 $file.mrc $file_binned.mrc >> output.txt


###############################################################
#" Move, rename, and delete junk of ${i}_driftcorr.mrc "
###############################################################
  mv $file_binned.mrc driftcorr_mrc
  mv ${i} Finished_tif
done

exit 1

