#!/bin/bash

############################################################################
# OJcryo_relion_rm_duplicates.sh removes all duplicate particles from
# a join_particles.star file made in RELION. Does the same for join_mics.star
# files as well. It should be run directly after joining star files *if* you 
# get a warning that you have duplicates.
#
# Written by Austin Dixon
#
###########################################################################

display_usage()
{
  printf "****************************\n- Navigate to a JoinStar/ folder that contains a join_particles.star or join_mics.star file."
  printf "\n- RUN (for particles): OJcryo_relion_rm_duplicates -p <star file>"
  printf "\n- RUN (for micrographs): OJcryo_relion_rm_duplicates -m <star file>" 
  printf "\n- Output: join_particles_no_duplicates.star for particles // join_mics_no_duplicates.star for micrographs\n****************************\n"
}

# check for input
if [ ! $1 ]
then
 printf "ERROR: No input given!\n"
 display_usage
 exit 0
fi

# check whether user supplied help tag
if [[ ($1 == "--help") ||  ($1 == "-h") ||  ($1 == "--h") || ($1 == "-help") || ($1 == "usage")]]
then
    	display_usage
        exit 0
fi

#---------------------------------------------------------#
#			MAIN SCRIPT			  #
#---------------------------------------------------------#

mode=$1
INPUT=$2

if [ $mode == "-m" ]	# micrograph mode
then
 awk -F"\t" '!uniq[$0]++' $INPUT >> join_mics_no_duplicates.star
 oldnum=($(wc $INPUT))		# get number of lines in old file
 newnum=($(wc join_mics_no_duplicates.star))		# get number of lines in new file
 deleted=$((${oldnum[0]} - ${newnum[0]} + 1))	# get number of particles eliminated ('-1' is because of newline made during append >>)

 # Tell user what happened
 printf "DONE: join_particles_no_duplicates.star was written, $deleted duplicates were removed.\n"

elif [ $mode == "-p" ]	# particle mode
then
 awk -F"\t" '!uniq[$0]++' $INPUT >> join_mics_no_duplicates.star
 oldnum=($(wc $INPUT))		# get number of lines in old file
 newnum=($(wc join_particles_no_duplicates.star))	# get number of lines in new file
 deleted=$((${oldnum[0]} - ${newnum[0]} + 1))	# get number of particles eliminated ('+ 1' is because of newline made during append >>)

 # Tell user what happened
 printf "DONE: join_mics_no_duplicates.star was written, $deleted duplicates were removed.\n"
 
else
 printf "Please specify a mode for removing duplicates!\n"
 display_usage
fi
